version: '3.8'
services:
  app:
    build: .
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    environment:
      DEBUG: 1
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: exchange_bot